sonarqube-check:
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
    
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
    GIT_DEPTH: "0" 
    SONAR_TOKEN: "sqp_b2ee609e207cb60c963803067963f8f9cc5eb6eb"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  tags:
    - dev  
  script: 
    - sonar-scanner -Dsonar.projectKey=sps_odoo -Dsonar.qualitygate.wait=true -Dsonar.login=${SONAR_TOKEN} -Dsonar.host.url=http://10.108.0.9:9000
  allow_failure: true
  only:
    - bits_merge_all